os: linux
dist: trusty
sudo: false
language: python
python: 3.6
cache:
  apt: true
  ccache: true
addons:
  apt:
    packages:
      - "python3-pip"
      - "libcap-dev"
      - "libidn2-0-dev"
      - "nettle-dev"
matrix:
  include:
    - env: CC=gcc
    - env: CC=clang
install:
  - export NINJA_LATEST=$(curl --silent https://api.github.com/repos/ninja-build/ninja/releases/latest | awk --field-separator='"' '/browser_download_url.*ninja-linux.zip/ {print $4}')
  - wget "$NINJA_LATEST"
  - unzip -q ninja-linux.zip -d build
  - export PATH="$PWD/build:$PATH"
  - pip3 install meson
script:
  - meson builddir
  - ninja -C builddir
