language: c
before_install:
  - sudo apt-get update
  - sudo apt-get install libcap-dev
compiler:
  - gcc
  - clang
env:
  matrix:
    - USE_CAP=true
    - USE_CAP=false
    - USE_IDN=true
    - USE_IDN=false
script: make

